### ISSUE TITLE
doesn't work?

### ISSUE THREAD

**Issue by JaceThings** [hanikesn/woff2otf#16]
I tried to run the command, but I get this error, idk what the problem could be...
```
bred@BredBook woff2otf-master % python3 woff2otf.py Beausite-Classic_BoldItalic.woff Beausite-Classic_BoldItalic.ttf
Traceback (most recent call last):
  File "/Users/bred/Desktop/woff2otf-master/woff2otf.py", line 110, in <module>
    sys.exit(main(sys.argv))
  File "/Users/bred/Desktop/woff2otf-master/woff2otf.py", line 105, in main
    convert(source_file_name, target_file_name)
  File "/Users/bred/Desktop/woff2otf-master/woff2otf.py", line 89, in convert
    convert_streams(infile, outfile)
  File "/Users/bred/Desktop/woff2otf-master/woff2otf.py", line 43, in convert_streams
    outfile.write(struct.pack(">H", searchRange));
struct.error: 'H' format requires 0 <= number <= 65535
```

**Comment by hanikesn** [comment]
Are you sure the file is not in WOFF2 format?

**Comment by JaceThings** [comment]
nope, they were in WOFF, I can give some to you if you'd like to try.
[Font.zip](https://github.com/hanikesn/woff2otf/files/8566328/Font.zip)

**Comment by blakeperdue** [comment]
Looks like there might be an issue running this on more recent Python versions? I am getting the same errors as @Soft-Bred. @hanikesn any ideas? Thanks for any help!!

**Comment by blakeperdue** [comment]
Yea, tracing the code it looks like offset is getting set high (`offset=6477797044`) which causes line 63 to error:

```
outfile.write(struct.pack(">I", offset))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: 'I' format requires 0 <= number <= 4294967295
```

**Comment by hanikesn** [comment]
@blakeperdue Can you please upload/link a woff file that's causing the issue.

**Comment by ochen1** [comment]
@hanikesn Here's an example file that causes such an issue:

https://font-public.canva.com/YADZ-ZLzliU/0/Catalogue-Reg_2B6615975169921869409.c7abe42c1adc5f30f10d779e594b1987.otf

Alternatively,

[Anastasia-Script_Regular.a2cc81459984b42.8db1cca60c1d1aa8ba2baa88a7d6dd4.zip](https://github.com/user-attachments/files/15813468/Anastasia-Script_Regular.a2cc81459984b42.8db1cca60c1d1aa8ba2baa88a7d6dd4.zip)

**Comment by Gabrieloxe** [comment]
I am experiencing the same issue on python 3.10.4

**Comment by bertrandperrier** [comment]
i have the same problem

> struct.error: 'I' format requires 0 <= number <= 4294967295

[url](https://fonts.gstatic.com/s/materialicons/v37/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2)
