### ISSUE TITLE
struct.error: 'H' format requires 0 <= number <= 65535

### ISSUE THREAD

**Issue by michalczaplinski** [hanikesn/woff2otf#7]
I keep receiving the following traceback:

    [user@machine] $ python3 woff2otf.py font1.woff font1.otf
    Traceback (most recent call last):
     File "woff2otf.py", line 111, in <module>
        sys.exit(main(sys.argv))
      File "woff2otf.py", line 106, in main
        convert(source_file_name, target_file_name)
      File "woff2otf.py", line 90, in convert
        convert_streams(infile, outfile)
      File "woff2otf.py", line 44, in convert_streams
        outfile.write(struct.pack(">H", searchRange));
    struct.error: 'H' format requires 0 <= number <= 65535

I can upload the file I try to convert to a suitable location if you wish to test this.

**Comment by michalczaplinski** [comment]
Closed - the issue was the corrupt .woff file.
